name: GestionSystem
version: 0.0.1
description: A minimal web app for the developer that doesnâ€™t want to be confused by too much going on.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  angular: any
  browser: any
  googleapis: any
  googleapis_auth: any
  redstone: any
  redstone_mapper: any
  redstone_mapper_mongo: any
  route_hierarchical: '>=0.5.0 <0.7.0'
  sass: '>=0.4.0 <0.5.0'
  script_inliner: '>=1.0.0 <2.0.0'
  shelf: any
  shelf_static: any
  unittest: any
transformers:
- script_inliner
- redstone_mapper
- angular:
    html_files:
    - lib/components/login/login.html
    - lib/components/login/nuevo_usuario.html
    - lib/components/home/home.html
    - lib/components/evento/evento.html
    - lib/components/vista/vista.html
    - lib/components/vista/construccion_ra/construccion_ra.html
    - lib/components/admin/admin.html
    - lib/components/admin/model.html
    - lib/components/admin/target.html
    - lib/components/widgets/loader/loader.html
    - lib/components/widgets/alert/alert.html
    - lib/components/widgets/dummy/dummy.html
- $dart2js:
    $exclude:
    - bin
    - '*test*'
    minify: true
